# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
CLOUDINARY_URL: "cloudinary://269666261817264:XxL0jVnDRx4pFeNz9qwV7AlOUmk@serendipity"

development:
  FB_ID: "1430715123607580"
  FB_SECRET: 34dfe3bf38262882f3183d8c0d5f55ae
  # TODO change with real keys for launch after testing
  STRIPE_PUBLISHABLE_KEY: pk_test_Ky9cibFg1knD47YxIyIW8sYa
  STRIPE_SECRET_KEY: sk_test_sLWPL6g2oggwv1WVGXSnmzdu
  MAILCHIMP_API_KEY: 3ecdb57184d46324073ae982ed9b5167-us14
  MAILCHIMP_LIST_ID: 7d0e28cc2b
  GOOGLE_API_BROWSER_KEY: AIzaSyAxopeDgDJv7XVoOGL1nBtCxM_hF_ObTvE
production:
  FB_ID: "1430713150274444"
  FB_SECRET: 4c5e09d01b8702f067163b316bb1b1b9
  # TODO change with real keys for launch after testing
  STRIPE_PUBLISHABLE_KEY: pk_test_Ky9cibFg1knD47YxIyIW8sYa
  STRIPE_SECRET_KEY: sk_test_sLWPL6g2oggwv1WVGXSnmzdu
  MAILCHIMP_API_KEY: 3ecdb57184d46324073ae982ed9b5167-us14
  MAILCHIMP_LIST_ID: 7d0e28cc2b
  GOOGLE_API_BROWSER_KEY: AIzaSyAxopeDgDJv7XVoOGL1nBtCxM_hF_ObTvE
