# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0419136a8cc5ef37c08f4f42264f77136e4b057de2b567c4174149d2fe53eb5ef4a45889fc96a0e4e9edafff40ffdcc39011494c4b47d24cc97a82b88357ff96

test:
  secret_key_base: fd8eff6afcf9c8c395498a8a127f6fd3af19c6264f77b1f8479b30bdfc25d4209deb9dcbb07c2111ca829a72996f3850128870b8817c9bb6658d50e52818404a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
